### ISSUE TITLE
Add comments and documentation to all classes

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/PhysicalStats#1]
Currently, all of the classes in this module are lacking documentation. So, the goal of this would be to add Javadoc comments to all of the classes.

Thankfully, it shouldn't be too difficult as several classes are similar to each other.

**Comment by xrtariq2594** [comment]
Documentation has been added in [this commit](https://github.com/Terasology/PhysicalStats/commit/0cbbf071cc1621d6ed53d69679e68d1718d1a238).

**Comment by Cervator** [comment]
Closing as completed by #2
